-- =========================================================================
-- supabase_general.sql
--   "General" lessons + lesson share codes + search-friendly indexes.
--
--   - General lessons live in public.lessons with is_general = true and
--     topic_id = NULL. Staff tag them with `tags text[]` to make them
--     findable.
--   - Every published lesson gets a 5-char share code (e.g. XK4F2) on
--     first publish, generated by publish_lesson(). Unpublish keeps the
--     code; re-publish reuses it.
--   - pg_trgm is required for the title ilike index.
--
--   Run order: append after supabase_units.sql. All statements are
--   idempotent.
-- =========================================================================

create extension if not exists pg_trgm;

-- ---------- 1. SCHEMA CHANGES --------------------------------------------

-- topic_id is now optional: it's NULL for general lessons.
alter table public.lessons alter column topic_id drop not null;

-- New columns.
alter table public.lessons
  add column if not exists is_general boolean not null default false,
  add column if not exists tags       text[]   not null default '{}',
  add column if not exists code       text;

-- Invariant: a lesson is either in a topic OR a general lesson, never both.
-- We add the constraint in a way that doesn't break existing data:
-- all existing rows have is_general=false AND topic_id NOT NULL, so they're
-- fine. The constraint will catch any future bad writes.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'lessons_general_or_topic_chk'
  ) then
    alter table public.lessons
      add constraint lessons_general_or_topic_chk
      check ((is_general = true  and topic_id is null)
          or (is_general = false and topic_id is not null));
  end if;
end $$;

-- ---------- 2. INDEXES ---------------------------------------------------

create unique index if not exists lessons_code_uniq
  on public.lessons (code) where code is not null;

create index if not exists lessons_is_general_idx
  on public.lessons (is_general) where is_general = true;

create index if not exists lessons_tags_gin
  on public.lessons using gin (tags);

create index if not exists lessons_title_trgm
  on public.lessons using gin (title gin_trgm_ops);

-- ---------- 3. CODE GENERATION -------------------------------------------
--
-- A short, unambiguous 5-char code from the alphabet
--   ABCDEFGHJKLMNPQRSTUVWXYZ23456789
-- (drops I, O, 0, 1 — the visually ambiguous characters). 32^5 = ~33M
-- combinations, plenty for a single-tenant catalog and short enough to
-- type from a whiteboard. The function retries on the (vanishingly
-- rare) unique-collision and gives up after 10 attempts.

create or replace function public._generate_lesson_code()
returns text
language plpgsql
volatile
as $$
declare
  alphabet text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  result   text := '';
  i        int;
  pos      int;
  bytes    bytea;
begin
  for attempt in 1..10 loop
    bytes := gen_random_bytes(5);
    result := '';
    for i in 0..4 loop
      pos := 1 + (get_byte(bytes, i) % length(alphabet));
      result := result || substr(alphabet, pos, 1);
    end loop;
    if not exists (select 1 from public.lessons where code = result) then
      return result;
    end if;
  end loop;
  raise exception 'could not generate unique lesson code after 10 attempts';
end;
$$;

-- ---------- 4. UPDATED publish_lesson RPC --------------------------------
--
-- Replaces the version in supabase_admin.sql. Generates the code on
-- the first publish and returns it in the JSONB response so the
-- creator can show the chip. Unpublish leaves the code intact; a
-- re-publish reuses the existing code (or generates one if for some
-- reason the column is NULL — e.g. a row that pre-dates this file).

create or replace function public.publish_lesson(
  p_lesson_id uuid,
  p_publish   boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_caller uuid := auth.uid();
  v_lesson public.lessons%rowtype;
  v_new_status text;
  v_code       text;
begin
  if v_caller is null then
    raise exception 'not authenticated';
  end if;
  if not exists (
    select 1 from public.profiles
     where id = v_caller
       and role in ('staff_reviewer', 'admin')
  ) then
    raise exception 'reviewer or admin role required' using errcode = '42501';
  end if;
  select * into v_lesson from public.lessons where id = p_lesson_id;
  if not found then
    return jsonb_build_object('ok', false, 'reason', 'unknown_lesson');
  end if;

  if p_publish then
    v_new_status := 'published';
    v_code := coalesce(v_lesson.code, public._generate_lesson_code());
    update public.lessons
       set status       = v_new_status,
           published_at = now(),
           published_by = v_caller,
           code         = v_code
     where id = p_lesson_id;
    perform public._log_staff_action(
      'lesson_published', 'lesson', p_lesson_id,
      jsonb_build_object('title', v_lesson.title, 'code', v_code)
    );
  else
    v_new_status := 'draft';
    update public.lessons
       set status       = v_new_status,
           published_at = null,
           published_by = null
     where id = p_lesson_id;
    -- Intentionally do NOT clear `code`: re-publishing should reuse it.
    v_code := v_lesson.code;
    perform public._log_staff_action(
      'lesson_unpublished', 'lesson', p_lesson_id,
      jsonb_build_object('title', v_lesson.title, 'code', v_code)
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'status', v_new_status,
    'code', v_code,
    'published_at', case when p_publish then now() else null end
  );
end;
$$;

grant execute on function public.publish_lesson(uuid, boolean) to authenticated;
grant execute on function public._generate_lesson_code()       to authenticated;
