-- ============================================================================
-- Recall Education — Email confirmation via custom Resend email
-- Run this AFTER all other migration files. Idempotent: safe to re-run.
--
-- What this does:
--   1. Adds a SECURITY DEFINER RPC `confirm_my_email()` that the
--      /auth/confirmed*.html pages call after the user is signed in
--      via the magic link from the Resend email.
--
-- Why this exists:
--   We replaced Supabase's built-in "Confirm signup" email with our own
--   Resend-branded email (sent from the send-signup-email Edge Function,
--   which is client-invoked rather than a hook). The Resend email
--   contains a magic link generated by supabase.auth.admin.generateLink.
--   When the user clicks the link, they're signed in — but their
--   email_confirmed_at is NOT set, because the magic link flow doesn't
--   update that field.
--
--   Supabase's auth server requires email_confirmed_at to be set
--   before the user can sign in via password. The user's only sign-in
--   path right now is the magic link itself, so this isn't blocking
--   anyone — but the auth.users row should still be marked as
--   confirmed for downstream consumers (admin tools, future "change
--   email" flows, etc).
--
--   The RPC is SECURITY DEFINER + auth.uid() gated, so the only thing
--   it can do is set the caller's own email_confirmed_at. No way to
--   confirm someone else's email.
-- ============================================================================

-- ---------- 1. confirm_my_email() ----------------------------------------

create or replace function public.confirm_my_email()
returns timestamptz
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid;
  v_existing timestamptz;
begin
  v_uid := auth.uid();
  if v_uid is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;

  -- Idempotent: if the email is already confirmed, return the existing
  -- timestamp. Otherwise stamp it now.
  select email_confirmed_at into v_existing
    from auth.users
    where id = v_uid;
  if v_existing is not null then
    return v_existing;
  end if;

  update auth.users
    set email_confirmed_at = now(),
        updated_at = now()
    where id = v_uid
      and email_confirmed_at is null;

  return now();
end;
$$;

grant execute on function public.confirm_my_email() to authenticated;
